# Generated by Django 3.1.1 on 2021-05-01 10:48

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('profile_photo', models.ImageField(upload_to=teacher.models.path_and_rename_teacher, verbose_name='Faculty Pic')),
                ('experience', models.IntegerField()),
                ('languages', models.CharField(max_length=100)),
                ('about', ckeditor.fields.RichTextField()),
                ('qualification', ckeditor.fields.RichTextField()),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('facebook_link', models.CharField(blank=True, max_length=100)),
                ('twitter_link', models.CharField(blank=True, max_length=100)),
                ('linkedin_link', models.CharField(blank=True, max_length=100)),
                ('instagram_link', models.CharField(blank=True, max_length=100)),
                ('programming_skills_percentage', models.IntegerField()),
                ('communication_skiils_percentage', models.IntegerField()),
                ('teching_skills_percentage', models.IntegerField()),
                ('achievements', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(to='subjects.Subject')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.branch')),
            ],
        ),
    ]
