# Generated by Django 3.1.1 on 2021-05-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='communication_skiils_percentage',
            new_name='communication_skills_percentage',
        ),
    ]
