# Generated by Django 3.1.1 on 2021-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210502_0917'),
        ('teacher', '0003_auto_20210502_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(to='subjects.SubjectDescription'),
        ),
    ]
