# Generated by Django 3.1.1 on 2021-05-05 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
