# Generated by Django 3.1.1 on 2021-05-01 10:36

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('couse_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('subj_image', models.ImageField(upload_to=subjects.models.path_and_rename_subj, verbose_name='Subject Pic')),
                ('subj_image_2', models.ImageField(blank=True, upload_to=subjects.models.path_and_rename_subj, verbose_name='Subject Pic2')),
                ('subj_image_3', models.ImageField(blank=True, upload_to=subjects.models.path_and_rename_subj, verbose_name='Subject Pic3')),
                ('branch', models.ManyToManyField(to='subjects.Branch')),
                ('course', models.ManyToManyField(to='subjects.Course')),
                ('sem', models.ManyToManyField(to='subjects.Sem')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', ckeditor.fields.RichTextField()),
                ('description_2', ckeditor.fields.RichTextField()),
                ('description_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('course_out_come_1', models.TextField(max_length=400)),
                ('course_out_come_2', models.TextField(max_length=400)),
                ('course_out_come_3', models.TextField(max_length=400)),
                ('course_out_come_4', models.TextField(max_length=400)),
                ('course_out_come_5', models.TextField(max_length=400)),
                ('course_out_come_6', models.TextField(max_length=400)),
                ('course_out_come_7', models.TextField(max_length=400)),
                ('course_out_come_8', models.TextField(max_length=400)),
                ('course_out_come_9', models.TextField(max_length=400)),
                ('course_out_come_10', models.TextField(max_length=400)),
                ('Chapter_1_title', models.CharField(max_length=100)),
                ('Chapter_2_title', models.CharField(max_length=100)),
                ('Chapter_3_title', models.CharField(max_length=100)),
                ('Chapter_4_title', models.CharField(max_length=100)),
                ('Chapter_5_title', models.CharField(max_length=100)),
                ('Chapter_6_title', models.CharField(blank=True, max_length=100)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='sem',
            field=models.ManyToManyField(to='subjects.Sem'),
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ManyToManyField(to='subjects.Course'),
        ),
    ]
