# Generated by Django 3.1.1 on 2021-05-03 04:04

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_course_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_img_2',
            field=models.ImageField(blank=True, upload_to=subjects.models.path_and_rename_course, verbose_name='Course Pic'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_img_3',
            field=models.ImageField(blank=True, upload_to=subjects.models.path_and_rename_course, verbose_name='Course Pic'),
        ),
    ]
