# Generated by Django 3.1.1 on 2021-05-07 09:08

import ckeditor.fields
from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210503_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chpater_name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('pdf_material', models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter, verbose_name='Chapter Pic')),
                ('pdf_material_1', models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter, verbose_name='Chapter Pic')),
                ('pdf_material_2', models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter, verbose_name='Chapter Pic')),
                ('pdf_material_3', models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter, verbose_name='Chapter Pic')),
                ('pdf_link', models.URLField(blank=True, max_length=500, null=True)),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
                ('topics', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_1_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_2_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_3_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_4_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_5_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='Chapter_6_title',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_1',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_10',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_2',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_3',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_4',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_5',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_6',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_7',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_8',
        ),
        migrations.RemoveField(
            model_name='subjectdescription',
            name='course_out_come_9',
        ),
        migrations.AddField(
            model_name='subject',
            name='chapter',
            field=models.ManyToManyField(to='subjects.Chapter'),
        ),
    ]
