# Generated by Django 3.1.1 on 2021-05-07 10:34

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20210507_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chpater_name',
            new_name='chapter_name',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pdf_material',
            field=models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pdf_material_1',
            field=models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pdf_material_2',
            field=models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pdf_material_3',
            field=models.FileField(blank=True, upload_to=subjects.models.path_and_rename_chapter),
        ),
    ]
