# Generated by Django 3.1.1 on 2021-05-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20210507_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='question_papers',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
